### ISSUE TITLE
Setup DSM

### ISSUE THREAD

**Issue by ghost** [GitaVYBE/VYBE-pm#51]
Dragon Surge Media, or >DSM<, is a partner of VYBE and would greatly appreciate any and all help that can be spared

**Comment by GitaVYBE** [comment]
@Kailestis Can you provide some information on DSM? Will this be another channel of VYBE? What does DSM focus on? What kind of help is needed? TYSM

**Comment by GitaVYBE** [comment]
@VYBETRIBE FYI
